// Site behaviours — generated by GalSol
(function(){
  // scroll reveal
  var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target);}});},{threshold:.12,rootMargin:'0px 0px -8% 0px'});
  document.querySelectorAll('.reveal').forEach(function(el){io.observe(el);});

  // mobile nav
  document.querySelectorAll('[data-burger]').forEach(function(b){
    b.addEventListener('click',function(){var n=b.closest('[data-nav]');if(n)n.classList.toggle('open');});
  });
  document.querySelectorAll('[data-nav] .nav-links a').forEach(function(a){
    a.addEventListener('click',function(){var n=a.closest('[data-nav]');if(n)n.classList.remove('open');});
  });

  // countdowns
  document.querySelectorAll('[data-countdown]').forEach(function(cd){
    var target=new Date(cd.getAttribute('data-countdown')).getTime();
    if(isNaN(target))return;
    function pad(v){return (v<10?'0':'')+v;}
    function set(k,v){var el=cd.querySelector('[data-cd="'+k+'"]');if(el)el.textContent=pad(v);}
    function tick(){
      var d=target-Date.now();if(d<0)d=0;
      set('days',Math.floor(d/864e5));
      set('hours',Math.floor(d%864e5/36e5));
      set('mins',Math.floor(d%36e5/6e4));
      set('secs',Math.floor(d%6e4/1e3));
    }
    tick();setInterval(tick,1000);
  });
})();


/* ── effects kit ── */
(function(){
/* fx:data-typewriter */
  document.querySelectorAll('[data-typewriter]').forEach(function(el){
    var words=(el.getAttribute('data-typewriter')||el.textContent||'').split('|').filter(Boolean);
    if(!words.length)return; el.textContent=''; var wi=0,ci=0,del=false;
    (function loop(){ var w=words[wi%words.length];
      el.textContent=w.slice(0,ci); el.classList.add('tw-caret');
      if(!del){ ci++; if(ci>w.length){del=true; return setTimeout(loop,1400);} }
      else { ci--; if(ci<0){del=false; wi++; ci=0; return setTimeout(loop,180);} }
      setTimeout(loop, del?45:75);
    })();
  });
/* fx:data-flip */
  document.querySelectorAll('[data-flip]').forEach(function(el){
    var words=(el.getAttribute('data-flip')||'').split('|').filter(Boolean); if(!words.length)return;
    var s=document.createElement('span'); s.textContent=words[0]; el.textContent=''; el.appendChild(s); var i=0;
    setInterval(function(){ s.style.opacity='0'; s.style.transform='rotateX(-90deg)';
      setTimeout(function(){ i=(i+1)%words.length; s.textContent=words[i]; s.style.transform='rotateX(90deg)';
        requestAnimationFrame(function(){ s.style.opacity='1'; s.style.transform='none'; }); },500);
    },2600);
  });
/* fx:data-magnetic */
  document.querySelectorAll('[data-magnetic]').forEach(function(el){
    el.style.transition='transform .2s var(--ease,ease)';
    el.addEventListener('mousemove',function(e){var r=el.getBoundingClientRect();el.style.transform='translate('+((e.clientX-r.left-r.width/2)*.25)+'px,'+((e.clientY-r.top-r.height/2)*.35)+'px)';});
    el.addEventListener('mouseleave',function(){el.style.transform='';});
  });
/* fx:data-tilt */
  document.querySelectorAll('[data-tilt]').forEach(function(el){
    el.style.transition='transform .2s var(--ease,ease)';el.style.transformStyle='preserve-3d';
    el.addEventListener('mousemove',function(e){var r=el.getBoundingClientRect();var x=(e.clientX-r.left)/r.width-.5;var y=(e.clientY-r.top)/r.height-.5;el.style.transform='perspective(900px) rotateY('+(x*9)+'deg) rotateX('+(-y*9)+'deg)';});
    el.addEventListener('mouseleave',function(){el.style.transform='';});
  });
/* fx:data-glow */
  document.querySelectorAll('[data-glow]').forEach(function(el){
    el.addEventListener('mousemove',function(e){var r=el.getBoundingClientRect();el.style.setProperty('--gx',(e.clientX-r.left)+'px');el.style.setProperty('--gy',(e.clientY-r.top)+'px');});
  });
/* fx:data-spotlight */
  document.querySelectorAll('[data-spotlight]').forEach(function(el){
    el.addEventListener('mousemove',function(e){var r=el.getBoundingClientRect();el.style.setProperty('--spx',(e.clientX-r.left)+'px');el.style.setProperty('--spy',(e.clientY-r.top)+'px');});
  });
/* fx:data-sparkles */
  document.querySelectorAll('[data-sparkles]').forEach(function(el){
    var c=document.createElement('canvas');c.style.cssText='position:absolute;inset:0;z-index:0;pointer-events:none';
    if(getComputedStyle(el).position==='static')el.style.position='relative';
    el.insertBefore(c,el.firstChild); Array.prototype.forEach.call(el.children,function(ch){if(ch!==c)ch.style.position=ch.style.position||'relative';});
    var ctx=c.getContext('2d'),ps=[],DPR=Math.min(2,window.devicePixelRatio||1);
    function size(){c.width=el.clientWidth*DPR;c.height=el.clientHeight*DPR;}
    function make(){return{x:Math.random()*c.width,y:Math.random()*c.height,r:(Math.random()*1.4+.3)*DPR,a:Math.random(),s:Math.random()*.02+.004};}
    for(var i=0;i<70;i++)ps.push(make()); size();window.addEventListener('resize',size);
    var col=getComputedStyle(el).getPropertyValue('--accent')||'#fff';
    (function draw(){ctx.clearRect(0,0,c.width,c.height);ps.forEach(function(p){p.a+=p.s;var o=(Math.sin(p.a)*.5+.5);ctx.globalAlpha=o*.8;ctx.fillStyle=col.trim()||'#fff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();});ctx.globalAlpha=1;requestAnimationFrame(draw);})();
  });
/* fx:data-nav-spotlight */
  document.querySelectorAll('[data-nav-spotlight]').forEach(function(nav){
    var links=nav.querySelectorAll('a'); if(!links.length)return;
    var ind=document.createElement('div');ind.className='nav-ind';nav.appendChild(ind);
    function moveTo(el){if(!el)return;var nr=nav.getBoundingClientRect(),r=el.getBoundingClientRect();ind.style.left=(r.left-nr.left)+'px';ind.style.width=r.width+'px';}
    nav.addEventListener('mousemove',function(e){var r=nav.getBoundingClientRect();nav.style.setProperty('--nspx',(e.clientX-r.left)+'px');});
    links.forEach(function(a){a.addEventListener('mouseenter',function(){moveTo(a);});});
    nav.addEventListener('mouseleave',function(){nav.style.setProperty('--nspx','-999px');moveTo(nav.querySelector('a.active')||links[0]);});
    setTimeout(function(){moveTo(nav.querySelector('a.active')||links[0]);},80);
  });
/* fx:data-dock */
  document.querySelectorAll('[data-dock]').forEach(function(dock){
    var items=Array.prototype.slice.call(dock.children);
    dock.addEventListener('mousemove',function(e){items.forEach(function(it){var r=it.getBoundingClientRect();var d=Math.abs(e.clientX-(r.left+r.width/2));var s=Math.max(1,1.55-d/150);it.style.transform='scale('+s.toFixed(3)+') translateY('+(-(s-1)*16).toFixed(1)+'px)';});});
    dock.addEventListener('mouseleave',function(){items.forEach(function(it){it.style.transform='';});});
  });
/* fx:data-carousel */
  document.querySelectorAll('[data-carousel]').forEach(function(car){
    var track=car.querySelector('.car-track'); if(!track)return;
    var slides=Array.prototype.slice.call(track.querySelectorAll('.car-slide')); if(!slides.length)return;
    var prev=document.createElement('button');prev.className='car-btn car-prev';prev.setAttribute('aria-label','Previous');prev.innerHTML='&#8249;';
    var next=document.createElement('button');next.className='car-btn car-next';next.setAttribute('aria-label','Next');next.innerHTML='&#8250;';
    var dots=document.createElement('div');dots.className='car-dots';
    car.appendChild(prev);car.appendChild(next);car.appendChild(dots);
    slides.forEach(function(s,i){var d=document.createElement('button');d.className='car-dot'+(i?'':' on');d.setAttribute('aria-label','Slide '+(i+1));d.addEventListener('click',function(){s.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'});});dots.appendChild(d);});
    function step(dir){track.scrollBy({left:dir*(slides[0].offsetWidth+16),behavior:'smooth'});}
    prev.addEventListener('click',function(){step(-1);});next.addEventListener('click',function(){step(1);});
    track.addEventListener('scroll',function(){var c=track.scrollLeft+track.clientWidth/2,best=0,bd=1e9;
      slides.forEach(function(s,i){var d=Math.abs((s.offsetLeft+s.offsetWidth/2)-c);if(d<bd){bd=d;best=i;}});
      Array.prototype.forEach.call(dots.children,function(d,i){d.classList.toggle('on',i===best);});});
  });
/* fx:fx-meteors */
  document.querySelectorAll('.fx-meteors').forEach(function(el){
    for(var i=0;i<14;i++){var m=document.createElement('span');m.className='meteor';m.style.left=(Math.random()*100)+'%';m.style.animationDelay=(Math.random()*8).toFixed(2)+'s';m.style.animationDuration=(4+Math.random()*6).toFixed(2)+'s';el.insertBefore(m,el.firstChild);}
  });
/* fx:data-encrypt */
  document.querySelectorAll('[data-encrypt]').forEach(function(el){
    var box=document.createElement('div');box.className='enc';el.insertBefore(box,el.firstChild);
    var CH='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',n=0;
    function gen(){var s='';for(var i=0;i<900;i++)s+=CH.charAt(Math.floor(Math.random()*CH.length));return s;}
    box.textContent=gen();
    el.addEventListener('mousemove',function(e){var r=el.getBoundingClientRect();el.style.setProperty('--ex',(e.clientX-r.left)+'px');el.style.setProperty('--ey',(e.clientY-r.top)+'px');if((n++%5)===0)box.textContent=gen();});
  });
/* fx:data-stars */
  document.querySelectorAll('[data-stars]').forEach(function(el){
    var c=document.createElement('canvas');c.style.cssText='position:absolute;inset:0;z-index:0;pointer-events:none';
    if(getComputedStyle(el).position==='static')el.style.position='relative';
    el.insertBefore(c,el.firstChild);
    var ctx=c.getContext('2d'),DPR=Math.min(2,window.devicePixelRatio||1),st=[];
    var col=(getComputedStyle(el).getPropertyValue('--accent')||'').trim()||'#ffffff';
    function size(){c.width=Math.max(1,el.clientWidth*DPR);c.height=Math.max(1,el.clientHeight*DPR);}
    function init(){st=[];var n=Math.min(260,Math.floor(c.width*c.height/7000));for(var i=0;i<n;i++)st.push({x:Math.random()*c.width,y:Math.random()*c.height,r:(Math.random()*1.2+.25)*DPR,a:Math.random()*6.28,s:Math.random()*.03+.006,v:(Math.random()*.14+.03)*DPR});}
    size();init();window.addEventListener('resize',function(){size();init();});
    (function loop(){ctx.clearRect(0,0,c.width,c.height);
      st.forEach(function(p){p.a+=p.s;p.y+=p.v;if(p.y>c.height+2){p.y=-2;p.x=Math.random()*c.width;}
        ctx.globalAlpha=(Math.sin(p.a)*.5+.5)*.85;ctx.fillStyle=p.r>1.1*DPR?col:'#ffffff';
        ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();});
      ctx.globalAlpha=1;requestAnimationFrame(loop);})();
  });
/* fx:data-antigravity */
  document.querySelectorAll('[data-antigravity]').forEach(function(el){
    var c=document.createElement('canvas');c.style.cssText='position:absolute;inset:0;z-index:0;pointer-events:none';
    if(getComputedStyle(el).position==='static')el.style.position='relative';
    el.insertBefore(c,el.firstChild);
    var ctx=c.getContext('2d'),DPR=Math.min(2,window.devicePixelRatio||1),ps=[],mx=-9999,my=-9999,t=0;
    var col=(getComputedStyle(el).getPropertyValue('--accent')||'').trim()||'#8ab4ff';
    function size(){c.width=Math.max(1,el.clientWidth*DPR);c.height=Math.max(1,el.clientHeight*DPR);}
    function init(){ps=[];var n=Math.min(300,Math.floor(c.width*c.height/9000));for(var i=0;i<n;i++){var x=Math.random()*c.width,y=Math.random()*c.height;ps.push({hx:x,hy:y,x:x,y:y,o:Math.random()*6.28});}}
    size();init();window.addEventListener('resize',function(){size();init();});
    el.addEventListener('pointermove',function(e){var r=el.getBoundingClientRect();mx=(e.clientX-r.left)*DPR;my=(e.clientY-r.top)*DPR;});
    el.addEventListener('pointerleave',function(){mx=-9999;my=-9999;});
    var MAG=170*DPR,RING=95*DPR;
    (function loop(){t+=.02;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle=col;
      ps.forEach(function(p){var tx=p.hx,ty=p.hy;var dx=p.hx-mx,dy=p.hy-my,d=Math.sqrt(dx*dx+dy*dy);
        if(d<MAG){var a=Math.atan2(dy,dx);var rr=RING+Math.sin(t*2+a*3)*9*DPR;tx=mx+Math.cos(a)*rr;ty=my+Math.sin(a)*rr;}
        p.x+=(tx-p.x)*.08;p.y+=(ty-p.y)*.08;
        var dm=Math.sqrt((p.x-mx)*(p.x-mx)+(p.y-my)*(p.y-my));
        var near=Math.max(0,1-Math.abs(dm-RING)/(75*DPR));
        var s=(.7+Math.sin(t*3+p.o)*.3)*1.3*DPR*(.5+near);
        ctx.globalAlpha=.22+near*.78;ctx.beginPath();ctx.arc(p.x,p.y,s,0,7);ctx.fill();});
      ctx.globalAlpha=1;requestAnimationFrame(loop);})();
  });
/* fx:data-cursorgrid */
  document.querySelectorAll('[data-cursorgrid]').forEach(function(el){
    var c=document.createElement('canvas');c.style.cssText='position:absolute;inset:0;z-index:0;pointer-events:none';
    if(getComputedStyle(el).position==='static')el.style.position='relative';
    el.insertBefore(c,el.firstChild);
    var ctx=c.getContext('2d'),DPR=Math.min(2,window.devicePixelRatio||1);
    var CELL=70*DPR,RAD=150*DPR,cols=0,rows=0,offX=0,offY=0,al=new Float32Array(0),tt=new Float64Array(0),pulses=[];
    var raw=(getComputedStyle(el).getPropertyValue('--accent')||'').trim();
    function hex2rgb(h){if(!h||h.charAt(0)!=='#')return [138,180,255];h=h.slice(1);if(h.length===3)h=h.split('').map(function(x){return x+x;}).join('');var n=parseInt(h,16);return [(n>>16)&255,(n>>8)&255,n&255];}
    var C=hex2rgb(raw);
    function build(){c.width=Math.max(1,el.clientWidth*DPR);c.height=Math.max(1,el.clientHeight*DPR);cols=Math.ceil(c.width/CELL)+1;rows=Math.ceil(c.height/CELL)+1;offX=(c.width-cols*CELL)/2;offY=(c.height-rows*CELL)/2;al=new Float32Array(cols*rows);tt=new Float64Array(cols*rows);}
    build();window.addEventListener('resize',build);
    function cc(i){return [offX+(i%cols)*CELL+CELL/2,offY+Math.floor(i/cols)*CELL+CELL/2];}
    el.addEventListener('pointermove',function(e){var r=el.getBoundingClientRect(),x=(e.clientX-r.left)*DPR,y=(e.clientY-r.top)*DPR,now=performance.now();
      for(var i=0;i<al.length;i++){var p=cc(i),d=Math.sqrt((p[0]-x)*(p[0]-x)+(p[1]-y)*(p[1]-y));if(d>RAD)continue;var u=1-d/RAD,lv=u*u*(3-2*u);if(lv>al[i])al[i]=lv;tt[i]=now;}});
    el.addEventListener('pointerdown',function(e){var r=el.getBoundingClientRect();pulses.push({x:(e.clientX-r.left)*DPR,y:(e.clientY-r.top)*DPR,t0:performance.now()});});
    (function draw(){var now=performance.now();ctx.clearRect(0,0,c.width,c.height);
      for(var pi=pulses.length-1;pi>=0;pi--){var pu=pulses[pi],rr=(now-pu.t0)/1000*600*DPR;
        if(rr>Math.sqrt(c.width*c.width+c.height*c.height)){pulses.splice(pi,1);continue;}
        for(var k=0;k<al.length;k++){var q=cc(k),dd=Math.sqrt((q[0]-pu.x)*(q[0]-pu.x)+(q[1]-pu.y)*(q[1]-pu.y));if(Math.abs(dd-rr)<CELL/2){al[k]=1;tt[k]=now;}}}
      for(var i=0;i<al.length;i++){var a=al[i];if(a<=0)continue;
        if(now-tt[i]>400){a=Math.max(0,a-.02);al[i]=a;if(a<=0)continue;}
        var p=cc(i),g=ctx.createRadialGradient(p[0],p[1],CELL*.05,p[0],p[1],CELL);
        g.addColorStop(0,'rgba('+C[0]+','+C[1]+','+C[2]+','+a+')');g.addColorStop(1,'rgba('+C[0]+','+C[1]+','+C[2]+',0)');
        ctx.strokeStyle=g;ctx.lineWidth=1.2*DPR;ctx.strokeRect(p[0]-CELL/2+.5,p[1]-CELL/2+.5,CELL-1,CELL-1);}
      requestAnimationFrame(draw);})();
  });
/* fx:data-magnetlines */
  document.querySelectorAll('[data-magnetlines]').forEach(function(el){
    var cfg=(el.getAttribute('data-magnetlines')||'9x9').split('x');
    var rows=parseInt(cfg[0],10)||9, cols=parseInt(cfg[1],10)||9;
    el.style.gridTemplateColumns='repeat('+cols+',1fr)';el.style.gridTemplateRows='repeat('+rows+',1fr)';
    for(var i=0;i<rows*cols;i++)el.appendChild(document.createElement('span'));
    var items=el.querySelectorAll('span');
    window.addEventListener('pointermove',function(e){
      items.forEach(function(it){var r=it.getBoundingClientRect();var cx=r.left+r.width/2,cy=r.top+r.height/2;
        var b=e.clientX-cx,a=e.clientY-cy,cLen=Math.sqrt(a*a+b*b)||1;
        var deg=Math.acos(Math.max(-1,Math.min(1,b/cLen)))*180/Math.PI*(e.clientY>cy?1:-1);
        it.style.setProperty('--rot',deg.toFixed(1)+'deg');});
    });
  });
/* fx:data-clickspark */
  document.querySelectorAll('[data-clickspark]').forEach(function(el){
    var c=document.createElement('canvas');c.style.cssText='position:absolute;inset:0;z-index:3;pointer-events:none';
    if(getComputedStyle(el).position==='static')el.style.position='relative';
    el.appendChild(c);
    var ctx=c.getContext('2d'),DPR=Math.min(2,window.devicePixelRatio||1),sp=[];
    var col=(getComputedStyle(el).getPropertyValue('--accent')||'').trim()||'#ffffff';
    function size(){c.width=Math.max(1,el.clientWidth*DPR);c.height=Math.max(1,el.clientHeight*DPR);}
    size();window.addEventListener('resize',size);
    el.addEventListener('click',function(e){var r=el.getBoundingClientRect(),x=(e.clientX-r.left)*DPR,y=(e.clientY-r.top)*DPR,now=performance.now();
      for(var i=0;i<8;i++)sp.push({x:x,y:y,a:6.28318*i/8,t0:now});});
    (function draw(now){ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle=col;ctx.lineWidth=2*DPR;
      sp=sp.filter(function(s){var e=now-s.t0;if(e>=420)return false;var p=e/420,k=p*(2-p);
        var d=k*18*DPR,L=10*DPR*(1-k);
        ctx.beginPath();ctx.moveTo(s.x+d*Math.cos(s.a),s.y+d*Math.sin(s.a));
        ctx.lineTo(s.x+(d+L)*Math.cos(s.a),s.y+(d+L)*Math.sin(s.a));ctx.stroke();return true;});
      requestAnimationFrame(draw);})(performance.now());
  });
})();